version: "3.8"

services:
  database:
    container_name: db-postgre-movo
    image: postgres:15.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # default: /var/lib/postgresql/data better in a subfolder for volume mounts
      # see https://hub.docker.com/_/postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data



  # minio:
  #   container_name: minio-s3-movo
  #   image: minio/minio
  #   command: server /data --console-address ":9001"
  #   hostname: minio
  #   ports: 
  #     - 9000:9000
  #     - 9001:9001
  #   # environment:
  #     # MINIO_ROOT_USER: minioadmin
  #     # MINIO_ROOT_PASSWORD: minioadmin    
  #   volumes:
  #     - .minio:/data
